-- ==============================================================================
-- 6-QATLAM: BIZNES QOIDALAR VA AVTOMATLASHTIRISH
-- Ushbu kodni Supabase SQL Editor'da ishga tushiring.
-- ==============================================================================

-- Barcha xabarlar va qoidalarni log qilish uchun yordamchi jadval
CREATE TABLE IF NOT EXISTS public.system_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type text NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 1. HARAKAT BO'YICHA QOIDALAR (TRIGGERS)
-- ==============================================================================

-- QOIDA 1: Agar foydalanuvchi videoni to'liq ko'rsa, uni log qilish (yoki natijasini oshirish)
CREATE OR REPLACE FUNCTION public.rule_video_completed()
RETURNS trigger AS $$
BEGIN
    IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
        INSERT INTO public.system_logs (action_type, description)
        VALUES ('video_completed', 'Foydalanuvchi ' || NEW.user_id || ' videoni yakunladi: ' || NEW.video_id);
        
        -- Kelajakda foydalanuvchining ballini (progress) mana shu yerda oshirish mumkin
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_video_completed ON public.user_video_progress;
CREATE TRIGGER on_video_completed
    AFTER UPDATE ON public.user_video_progress
    FOR EACH ROW EXECUTE PROCEDURE public.rule_video_completed();


-- QOIDA 2: Foydalanuvchi testni 'finished' qilib yakunlasa va 90 balldan yuqori olsa, 
-- avtomatik tarzda "A'lochi" (Excellence) nishonini (badge) berish.
CREATE OR REPLACE FUNCTION public.rule_test_finished()
RETURNS trigger AS $$
DECLARE
    badge_id bigint;
BEGIN
    -- Agar test yakunlansa va natija >= 90 bo'lsa
    IF NEW.status = 'finished' AND NEW.score >= 90 THEN
        
        -- "A'lochi" nishoni bazada bor-yo'qligini tekshiramiz, yo'q bo'lsa yaratamiz
        SELECT id INTO badge_id FROM public.badges WHERE name = 'A''lochi' LIMIT 1;
        
        IF badge_id IS NULL THEN
            INSERT INTO public.badges (name, description, icon_url) 
            VALUES ('A''lochi', 'Testlardan 90% dan yuqori natija ko''rsatgani uchun', 'star')
            RETURNING id INTO badge_id;
        END IF;

        -- Foydalanuvchiga nishonni beramiz (agar avval berilmagan bo'lsa)
        INSERT INTO public.user_badges (user_id, badge_id)
        SELECT NEW.user_id, badge_id
        WHERE NOT EXISTS (
            SELECT 1 FROM public.user_badges 
            WHERE user_id = NEW.user_id AND badge_id = badge_id
        );

        -- Notification (Bildirishnoma) yuboramiz
        INSERT INTO public.notifications (user_id, title, body, type)
        VALUES (NEW.user_id, 'Tabriklaymiz!', 'Siz testdan ' || NEW.score || ' oldingiz va A''lochi nishonini qo''lga kiritdingiz!', 'system');

        -- Logga yozamiz
        INSERT INTO public.system_logs (action_type, description)
        VALUES ('badge_awarded', 'Foydalanuvchi ' || NEW.user_id || ' ga A''lochi nishoni berildi.');

    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_test_finished ON public.test_attempts;
CREATE TRIGGER on_test_finished
    AFTER UPDATE ON public.test_attempts
    FOR EACH ROW EXECUTE PROCEDURE public.rule_test_finished();


-- ==============================================================================
-- 2. TAYMER BO'YICHA QOIDALAR (CRON JOBS)
-- DIQQAT: pg_cron kengaytmasi Supabase'da sukut bo'yicha yoqilgan bo'lishi kerak.
-- ==============================================================================

-- Kerakli kengaytmani faollashtiramiz (agar yo'q bo'lsa)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- QOIDA 3: Har kuni soat tungi 00:00 da aktiv obunachilarga yangi kunlik vazifa (Today Tasks) yaratish.
-- Avval eski cron'ni o'chiramiz
SELECT cron.unschedule('generate_daily_tasks');
-- Yangi cron yaratamiz
SELECT cron.schedule('generate_daily_tasks', '0 0 * * *', $$
    INSERT INTO public.today_tasks (user_id, task_type, task_title, is_completed)
    SELECT user_id, 'video', 'Kunlik majburiy darsni ko''ring', false
    FROM public.user_subscriptions
    WHERE is_active = true AND end_date >= now();
$$);


-- QOIDA 4: Har kuni ertalab 08:00 da obunasi 3 kundan keyin tugaydigan foydalanuvchilarga bildirishnoma yuborish.
SELECT cron.unschedule('warn_expiring_subs');
SELECT cron.schedule('warn_expiring_subs', '0 8 * * *', $$
    INSERT INTO public.notifications (user_id, title, body, type)
    SELECT user_id, 'Obuna yakunlanmoqda', 'Sizning obunangiz 3 kundan so''ng tugaydi. Kurslarni davom ettirish uchun to''lov qiling.', 'system'
    FROM public.user_subscriptions
    WHERE is_active = true AND end_date::date = (now() + interval '3 days')::date;
$$);


-- Log
INSERT INTO public.system_logs (action_type, description) VALUES ('system_init', '6-qatlam (Biznes qoidalar va cron jobs) o''rnatildi.');
