-- Foydalanuvchilar (Users)
CREATE TABLE public.users (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  name text,
  phone text UNIQUE,
  telegram_chat_id text,
  avatar text,
  role text DEFAULT 'talaba' CHECK (role IN ('talaba', 'yordamchi', 'admin')),
  university text CHECK (university IN ('TDYU', 'JIDU')),
  level text CHECK (level IN ('boshlang''ich', 'o''rta', 'yuqori')),
  daily_study_hours numeric DEFAULT 2,
  exam_date date DEFAULT '2026-07-14',
  language text DEFAULT 'uz' CHECK (language IN ('uz', 'ru')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_active boolean DEFAULT true,
  auth_token text
);

-- Hafta kunlari (Schedule)
CREATE TABLE public.schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  day_of_week text CHECK (day_of_week IN ('dushanba', 'seshanba', 'chorshanba', 'payshanba', 'juma', 'shanba')),
  is_active boolean DEFAULT true,
  UNIQUE(user_id, day_of_week)
);

-- Oylik kurslar (Monthly Courses)
CREATE TABLE public.monthly_courses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_num integer NOT NULL,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  description_uz text,
  description_ru text,
  topic text,
  cover_image text,
  price numeric DEFAULT 450000,
  is_active boolean DEFAULT true
);

-- Foydalanuvchi obunalari (User Subscriptions)
CREATE TABLE public.user_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  purchased_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  premium_end_date date NOT NULL,
  materials_close_date date NOT NULL,
  payment_id bigint, -- will reference payments later
  is_active boolean DEFAULT true
);

-- Video darslar (Video Lessons)
CREATE TABLE public.video_lessons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  order_num integer NOT NULL,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  description_uz text,
  description_ru text,
  video_url text NOT NULL,
  duration_sec integer,
  cover_image text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Foydalanuvchi video holati (User Video Progress)
CREATE TABLE public.user_video_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  video_id bigint REFERENCES public.video_lessons(id) ON DELETE CASCADE,
  status text DEFAULT 'qulflangan' CHECK (status IN ('qulflangan', 'ochiq', 'ko''rilgan', 'o''tkazib yuborilgan')),
  unlock_date date,
  first_watched_at timestamp with time zone,
  last_position_sec integer DEFAULT 0,
  watched_percentage numeric DEFAULT 0,
  is_completed boolean DEFAULT false,
  UNIQUE(user_id, video_id)
);

-- Audio darslar (Audio Lessons)
CREATE TABLE public.audio_lessons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  audio_url text NOT NULL,
  duration_sec integer,
  order_num integer
);

-- PDF qo'llanmalar (PDF Guides)
CREATE TABLE public.pdf_guides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  pdf_url text NOT NULL,
  size_mb numeric,
  order_num integer
);

-- Qonunlar (Laws)
CREATE TABLE public.laws (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  content_uz text NOT NULL,
  content_ru text NOT NULL
);

-- Testlar (Tests)
CREATE TABLE public.tests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  test_type text CHECK (test_type IN ('video_test', 'oylik_test', 'mock_imtihon')),
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  video_id bigint REFERENCES public.video_lessons(id) ON DELETE CASCADE,
  duration_min integer,
  questions_count integer,
  mock_week integer,
  is_active boolean DEFAULT true
);

-- Test savollari (Test Questions)
CREATE TABLE public.test_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id bigint REFERENCES public.tests(id) ON DELETE CASCADE,
  question_uz text NOT NULL,
  question_ru text NOT NULL,
  option1_uz text NOT NULL,
  option1_ru text NOT NULL,
  option2_uz text NOT NULL,
  option2_ru text NOT NULL,
  option3_uz text NOT NULL,
  option3_ru text NOT NULL,
  option4_uz text NOT NULL,
  option4_ru text NOT NULL,
  correct_option integer CHECK (correct_option IN (1, 2, 3, 4)),
  explanation_uz text,
  explanation_ru text
);

-- Test urinishlari (Test Attempts)
CREATE TABLE public.test_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  test_id bigint REFERENCES public.tests(id) ON DELETE CASCADE,
  started_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  completed_at timestamp with time zone,
  spent_sec integer,
  total_score_percent numeric,
  correct_count integer DEFAULT 0,
  wrong_count integer DEFAULT 0,
  skipped_count integer DEFAULT 0,
  status text CHECK (status IN ('davom_etayotgan', 'tugatilgan', 'uzilgan')),
  is_latest boolean DEFAULT true
);

-- Test javoblari (Test Answers)
CREATE TABLE public.test_answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id bigint REFERENCES public.test_attempts(id) ON DELETE CASCADE,
  question_id bigint REFERENCES public.test_questions(id) ON DELETE CASCADE,
  user_option text CHECK (user_option IN ('1', '2', '3', '4', 'qoldirilgan')),
  is_correct boolean
);

-- Savollar (User questions)
CREATE TABLE public.user_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  video_id bigint REFERENCES public.video_lessons(id) ON DELETE CASCADE,
  text_content text NOT NULL,
  audio_url text,
  image_url text,
  status text DEFAULT 'javob_kutilmoqda' CHECK (status IN ('javob_kutilmoqda', 'javob_berilgan', 'o''chirilgan')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  likes_count integer DEFAULT 0,
  views_count integer DEFAULT 0,
  answered_by uuid REFERENCES public.users(id)
);

-- Javoblar (Teacher answers)
CREATE TABLE public.teacher_answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint REFERENCES public.user_questions(id) ON DELETE CASCADE,
  answered_by uuid REFERENCES public.users(id) ON DELETE CASCADE,
  display_name text DEFAULT 'Shalola Azizova',
  answer_type text CHECK (answer_type IN ('video', 'audio', 'matn')),
  video_url text,
  audio_url text,
  text_content text,
  duration_sec integer,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Izohlar (Comments)
CREATE TABLE public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint REFERENCES public.user_questions(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  text_content text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Yoqtirishlar (Likes)
CREATE TABLE public.likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  question_id bigint REFERENCES public.user_questions(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, question_id)
);

-- Yangiliklar (News)
CREATE TABLE public.news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_uz text NOT NULL,
  title_ru text NOT NULL,
  short_desc text,
  full_text text,
  life_example text,
  category text CHECK (category IN ('muhim_o''zgarish', 'yangi_qonun', 'tushuntirish', 'dolzarb')),
  cover_image text,
  course_id bigint REFERENCES public.monthly_courses(id),
  related_article text,
  source_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  is_approved boolean DEFAULT false,
  is_active boolean DEFAULT true
);

-- Yangilik o'qishlari (News Reads)
CREATE TABLE public.news_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  news_id bigint REFERENCES public.news(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  read_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(news_id, user_id)
);

-- Bugungi vazifalar (Today's Tasks)
CREATE TABLE public.today_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  date date NOT NULL,
  task_name text NOT NULL,
  task_type text CHECK (task_type IN ('video_ko''rish', 'test_yechish', 'savol_o''qish')),
  video_id bigint REFERENCES public.video_lessons(id),
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone
);

-- Yutuqlar (Badges)
CREATE TABLE public.badges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_uz text NOT NULL,
  name_ru text NOT NULL,
  description text,
  icon_name text,
  condition_text text
);

-- Foydalanuvchi yutuqlari (User Badges)
CREATE TABLE public.user_badges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  badge_id bigint REFERENCES public.badges(id) ON DELETE CASCADE,
  earned_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, badge_id)
);

-- To'lovlar (Payments)
CREATE TABLE public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  course_id bigint REFERENCES public.monthly_courses(id) ON DELETE CASCADE,
  amount numeric DEFAULT 450000,
  provider text CHECK (provider IN ('Payme', 'Click', 'Uzcard', 'Visa')),
  external_transaction_id text,
  status text CHECK (status IN ('kutilmoqda', 'muvaffaqiyatli', 'rad_etilgan')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  completed_at timestamp with time zone
);

-- Bildirishnomalar (Notifications)
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL,
  type text CHECK (type IN ('yangi_javob', 'yangi_video', 'motivatsiya', 'to''lov', 'yangilik', 'eslatma')),
  related_link text,
  is_read boolean DEFAULT false,
  sent_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Yuklab olishlar (Downloads)
CREATE TABLE public.downloads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  file_type text CHECK (file_type IN ('PDF', 'audio', 'video')),
  material_id bigint,
  downloaded_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Motivatsion iqtiboslar (Motivational Quotes)
CREATE TABLE public.motivational_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text_uz text NOT NULL,
  text_ru text NOT NULL,
  author text,
  is_active boolean DEFAULT true
);

-- Setup RLS (Row Level Security) Example for Users table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
