/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#411f68",
        "primary-container": "#4b0082",
        "surface-variant": "#e3e2e6",
        "on-tertiary-container": "#ae89d8",
        "inverse-on-surface": "#f1f0f4",
        "on-surface-variant": "#4c4451",
        "primary-fixed-dim": "#ddb7ff",
        "surface-container-low": "#f4f3f7",
        "background": "#faf9fd",
        "on-surface": "#1a1c1e",
        "on-secondary-fixed": "#241a00",
        "inverse-surface": "#2f3033",
        "outline": "#7d7483",
        "tertiary-fixed-dim": "#dab9ff",
        "on-background": "#1a1c1e",
        "secondary-fixed-dim": "#e9c349",
        "on-primary-container": "#ba7ef4",
        "on-tertiary": "#ffffff",
        "outline-variant": "#cec3d3",
        "surface-container-highest": "#e3e2e6",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "surface-container": "#eeedf1",
        "on-secondary-container": "#745c00",
        "surface": "#faf9fd",
        "on-primary-fixed-variant": "#622599",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "primary": "#2e0052",
        "inverse-primary": "#ddb7ff",
        "secondary-fixed": "#ffe088",
        "tertiary-fixed": "#eedbff",
        "tertiary": "#2b0452",
        "secondary": "#735c00",
        "surface-container-high": "#e8e8ec",
        "on-secondary": "#ffffff",
        "primary-fixed": "#f0dbff",
        "on-primary-fixed": "#2c0050",
        "on-tertiary-fixed": "#2a0251",
        "on-tertiary-fixed-variant": "#57367f",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#faf9fd",
        "surface-dim": "#dad9dd",
        "surface-tint": "#7b41b3",
        "secondary-container": "#fed65b",
        "success": "#2E7D32"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "xxl": "80px",
        "md": "16px",
        "sm": "8px",
        "gutter": "12px",
        "xl": "48px",
        "lg": "24px",
        "xs": "4px",
        "unit": "4px",
        "stack_md": "16px",
        "section_gap": "40px",
        "stack_sm": "4px",
        "stack_lg": "24px",
        "container_margin": "16px",
        "base": "8px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "h3": ["Newsreader", "serif"],
        "h2": ["Newsreader", "serif"],
        "h1": ["Newsreader", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Newsreader", "serif"],
        "body": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "700"}],
        "button": ["14px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.3", "letterSpacing": "0em", "fontWeight": "500"}],
        "h2": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
